### ISSUE TITLE
Create recipe cards (EPIC)

### ISSUE THREAD

**Issue by Marc-Jamie** [Marc-Jamie/nf-capstone#8]
As a User,
I want all the information of a recipe I need in one card,
so that know what im doing

AC

- [x] should contain recipe name
- [x] should contain time
- [x] should contain a description
- [x] should contain ingredients
- [x] should contain instructions
- [x] should contain "add to shoppinglist"
